[package]
name = "basic-desktop-calculator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = "1.4.27"
fltk-theme = "0.7.2"
regex = "1.10.4"
